#!/usr/bin/env python

#
# This is a fake STAR command for the execution of scripts
# in quick tutorial guide. The command will be put into
# ~/.sos/bin before execution.
#

import argparse
import os

# Rscript --default-packages=datasets,methods,utils,stats,grDevices,graphics 

def prepareOutput(output):
    if not os.path.isdir(os.path.split(output)[0]):
        os.makedirs(os.path.split(output)[0])
   
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('script')
    parser.add_argument('--default-packages')
    args, unknown_args = parser.parse_known_args()
    with open('myfigure.pdf', 'w') as pdf:
        pdf.write('fake pdf')
        print('Generating myfigure.pdf')


